
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.chemically.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.chemically.block.WitheriteBlock;
import net.mcreator.chemically.block.UraniumOreBlock;
import net.mcreator.chemically.block.UraniumDeepslateOreBlock;
import net.mcreator.chemically.block.UraniumBlockBlock;
import net.mcreator.chemically.block.TimeCrystalBlockBlock;
import net.mcreator.chemically.block.ThresholdStructureBlockBlock;
import net.mcreator.chemically.block.TemporalLampBlock;
import net.mcreator.chemically.block.SuperconductiveMagnetBlock;
import net.mcreator.chemically.block.SulfurOreBlock;
import net.mcreator.chemically.block.SulfurBlockBlock;
import net.mcreator.chemically.block.StoneTilesBlock;
import net.mcreator.chemically.block.StonePillarBlock;
import net.mcreator.chemically.block.SteelFactoryFloorBlock;
import net.mcreator.chemically.block.SteelBlockBlock;
import net.mcreator.chemically.block.SinusoidalWaveBlock;
import net.mcreator.chemically.block.SilverBlockBlock;
import net.mcreator.chemically.block.ServerBlock;
import net.mcreator.chemically.block.SandstoneFireTrapIgnitedBlock;
import net.mcreator.chemically.block.SandstoneFireTrapBlock;
import net.mcreator.chemically.block.RubyBlockBlock;
import net.mcreator.chemically.block.RedCautionBlock;
import net.mcreator.chemically.block.RawUraniumBlockBlock;
import net.mcreator.chemically.block.RawSilverBlockBlock;
import net.mcreator.chemically.block.RawNickelBlock;
import net.mcreator.chemically.block.RawLeadBlock;
import net.mcreator.chemically.block.RawAluminumBlockBlock;
import net.mcreator.chemically.block.RFCavityResonatorBlock;
import net.mcreator.chemically.block.QuartzLampBlock;
import net.mcreator.chemically.block.QuartzLampActiveBlock;
import net.mcreator.chemically.block.PurpleTulipBlock;
import net.mcreator.chemically.block.PowerCellBlock;
import net.mcreator.chemically.block.PowderedRedstineBlock;
import net.mcreator.chemically.block.PolishedEndstoneBlock;
import net.mcreator.chemically.block.PolarityDeviceBlock;
import net.mcreator.chemically.block.OnyxBlockBlock;
import net.mcreator.chemically.block.ObsidionBricksBlock;
import net.mcreator.chemically.block.ObsidianTilesBlock;
import net.mcreator.chemically.block.ObsidianRunesBlock;
import net.mcreator.chemically.block.LpmdsBlock;
import net.mcreator.chemically.block.LeadOreBlock;
import net.mcreator.chemically.block.LeadBlockBlock;
import net.mcreator.chemically.block.LaunchPadBlock;
import net.mcreator.chemically.block.LaboratoryBlockBlock;
import net.mcreator.chemically.block.JadeBlockBlock;
import net.mcreator.chemically.block.HydraulicPressBlock;
import net.mcreator.chemically.block.HighVelocityRotorBlock;
import net.mcreator.chemically.block.EndstonePillarBlock;
import net.mcreator.chemically.block.ElectromagneticFieldGeneratorBlock;
import net.mcreator.chemically.block.DeepslateSquaresBlock;
import net.mcreator.chemically.block.ConveyerBlock;
import net.mcreator.chemically.block.ChiseledStoneBrickPillarBlock;
import net.mcreator.chemically.block.ChiseledPurpurBlock;
import net.mcreator.chemically.block.ChiseledEndstoneBlock;
import net.mcreator.chemically.block.CautionBlock;
import net.mcreator.chemically.block.BronzeBlockBlock;
import net.mcreator.chemically.block.AsphaltBlock;
import net.mcreator.chemically.block.AsbestosBlock;
import net.mcreator.chemically.block.AquamarineBlockBlock;
import net.mcreator.chemically.block.AluminumDoorBlock;
import net.mcreator.chemically.block.AluminumBlockBlock;
import net.mcreator.chemically.block.AcceleratorBlock;
import net.mcreator.chemically.ChemicallyMod;

public class ChemicallyModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, ChemicallyMod.MODID);
	public static final RegistryObject<Block> SERVER = REGISTRY.register("server", () -> new ServerBlock());
	public static final RegistryObject<Block> CONVEYER = REGISTRY.register("conveyer", () -> new ConveyerBlock());
	public static final RegistryObject<Block> SINUSOIDAL_WAVE = REGISTRY.register("sinusoidal_wave", () -> new SinusoidalWaveBlock());
	public static final RegistryObject<Block> POLARITY_DEVICE = REGISTRY.register("polarity_device", () -> new PolarityDeviceBlock());
	public static final RegistryObject<Block> HYDRAULIC_PRESS = REGISTRY.register("hydraulic_press", () -> new HydraulicPressBlock());
	public static final RegistryObject<Block> POWER_CELL = REGISTRY.register("power_cell", () -> new PowerCellBlock());
	public static final RegistryObject<Block> ELECTROMAGNETIC_FIELD_GENERATOR = REGISTRY.register("electromagnetic_field_generator", () -> new ElectromagneticFieldGeneratorBlock());
	public static final RegistryObject<Block> ACCELERATOR = REGISTRY.register("accelerator", () -> new AcceleratorBlock());
	public static final RegistryObject<Block> LAUNCH_PAD = REGISTRY.register("launch_pad", () -> new LaunchPadBlock());
	public static final RegistryObject<Block> LABORATORY_BLOCK = REGISTRY.register("laboratory_block", () -> new LaboratoryBlockBlock());
	public static final RegistryObject<Block> CAUTION = REGISTRY.register("caution", () -> new CautionBlock());
	public static final RegistryObject<Block> RED_CAUTION = REGISTRY.register("red_caution", () -> new RedCautionBlock());
	public static final RegistryObject<Block> QUARTZ_LAMP = REGISTRY.register("quartz_lamp", () -> new QuartzLampBlock());
	public static final RegistryObject<Block> POWDERED_REDSTONE = REGISTRY.register("powdered_redstone", () -> new PowderedRedstineBlock());
	public static final RegistryObject<Block> TEMPORAL_LAMP = REGISTRY.register("temporal_lamp", () -> new TemporalLampBlock());
	public static final RegistryObject<Block> CHISELED_PURPUR = REGISTRY.register("chiseled_purpur", () -> new ChiseledPurpurBlock());
	public static final RegistryObject<Block> OBSIDIAN_BRICKS = REGISTRY.register("obsidian_bricks", () -> new ObsidionBricksBlock());
	public static final RegistryObject<Block> OBSIDIAN_TILES = REGISTRY.register("obsidian_tiles", () -> new ObsidianTilesBlock());
	public static final RegistryObject<Block> OBSIDIAN_RUNES = REGISTRY.register("obsidian_runes", () -> new ObsidianRunesBlock());
	public static final RegistryObject<Block> DEEPSLATE_SQUARES = REGISTRY.register("deepslate_squares", () -> new DeepslateSquaresBlock());
	public static final RegistryObject<Block> POLISHED_ENDSTONE = REGISTRY.register("polished_endstone", () -> new PolishedEndstoneBlock());
	public static final RegistryObject<Block> ENDSTONE_PILLAR = REGISTRY.register("endstone_pillar", () -> new EndstonePillarBlock());
	public static final RegistryObject<Block> SANDSTONE_FIRE_TRAP = REGISTRY.register("sandstone_fire_trap", () -> new SandstoneFireTrapBlock());
	public static final RegistryObject<Block> CHISELED_STONE_BRICK_PILLAR = REGISTRY.register("chiseled_stone_brick_pillar", () -> new ChiseledStoneBrickPillarBlock());
	public static final RegistryObject<Block> STONE_TILES = REGISTRY.register("stone_tiles", () -> new StoneTilesBlock());
	public static final RegistryObject<Block> STONE_PILLAR = REGISTRY.register("stone_pillar", () -> new StonePillarBlock());
	public static final RegistryObject<Block> CHISELED_ENDSTONE = REGISTRY.register("chiseled_endstone", () -> new ChiseledEndstoneBlock());
	public static final RegistryObject<Block> STEEL_FACTORY_FLOOR = REGISTRY.register("steel_factory_floor", () -> new SteelFactoryFloorBlock());
	public static final RegistryObject<Block> ALUMINUM_DOOR = REGISTRY.register("aluminum_door", () -> new AluminumDoorBlock());
	public static final RegistryObject<Block> PURPLE_TULIP = REGISTRY.register("purple_tulip", () -> new PurpleTulipBlock());
	public static final RegistryObject<Block> SULFUR_ORE = REGISTRY.register("sulfur_ore", () -> new SulfurOreBlock());
	public static final RegistryObject<Block> LEAD_ORE = REGISTRY.register("lead_ore", () -> new LeadOreBlock());
	public static final RegistryObject<Block> URANIUM_DEEPSLATE_ORE = REGISTRY.register("uranium_deepslate_ore", () -> new UraniumDeepslateOreBlock());
	public static final RegistryObject<Block> URANIUM_ORE = REGISTRY.register("uranium_ore", () -> new UraniumOreBlock());
	public static final RegistryObject<Block> HIGH_VELOCITY_ROTOR = REGISTRY.register("high_velocity_rotor", () -> new HighVelocityRotorBlock());
	public static final RegistryObject<Block> LPMDS = REGISTRY.register("lpmds", () -> new LpmdsBlock());
	public static final RegistryObject<Block> RF_CAVITY_RESONATOR = REGISTRY.register("rf_cavity_resonator", () -> new RFCavityResonatorBlock());
	public static final RegistryObject<Block> THRESHOLD_STRUCTURE_BLOCK = REGISTRY.register("threshold_structure_block", () -> new ThresholdStructureBlockBlock());
	public static final RegistryObject<Block> SUPERCONDUCTIVE_MAGNET = REGISTRY.register("superconductive_magnet", () -> new SuperconductiveMagnetBlock());
	public static final RegistryObject<Block> ASPHALT = REGISTRY.register("asphalt", () -> new AsphaltBlock());
	public static final RegistryObject<Block> ASBESTOS = REGISTRY.register("asbestos", () -> new AsbestosBlock());
	public static final RegistryObject<Block> STEEL_BLOCK = REGISTRY.register("steel_block", () -> new SteelBlockBlock());
	public static final RegistryObject<Block> AQUAMARINE_BLOCK = REGISTRY.register("aquamarine_block", () -> new AquamarineBlockBlock());
	public static final RegistryObject<Block> JADE_BLOCK = REGISTRY.register("jade_block", () -> new JadeBlockBlock());
	public static final RegistryObject<Block> ONYX_BLOCK = REGISTRY.register("onyx_block", () -> new OnyxBlockBlock());
	public static final RegistryObject<Block> RUBY_BLOCK = REGISTRY.register("ruby_block", () -> new RubyBlockBlock());
	public static final RegistryObject<Block> BRONZE_BLOCK = REGISTRY.register("bronze_block", () -> new BronzeBlockBlock());
	public static final RegistryObject<Block> WITHERITE = REGISTRY.register("witherite", () -> new WitheriteBlock());
	public static final RegistryObject<Block> URANIUM_BLOCK = REGISTRY.register("uranium_block", () -> new UraniumBlockBlock());
	public static final RegistryObject<Block> RAW_URANIUM_BLOCK = REGISTRY.register("raw_uranium_block", () -> new RawUraniumBlockBlock());
	public static final RegistryObject<Block> TIME_CRYSTAL_BLOCK = REGISTRY.register("time_crystal_block", () -> new TimeCrystalBlockBlock());
	public static final RegistryObject<Block> LEAD_BLOCK = REGISTRY.register("lead_block", () -> new LeadBlockBlock());
	public static final RegistryObject<Block> RAW_LEAD_BLOCK = REGISTRY.register("raw_lead_block", () -> new RawLeadBlock());
	public static final RegistryObject<Block> RAW_NICKEL_BLOCK = REGISTRY.register("raw_nickel_block", () -> new RawNickelBlock());
	public static final RegistryObject<Block> SILVER_BLOCK = REGISTRY.register("silver_block", () -> new SilverBlockBlock());
	public static final RegistryObject<Block> RAW_SILVER_BLOCK = REGISTRY.register("raw_silver_block", () -> new RawSilverBlockBlock());
	public static final RegistryObject<Block> ALUMINUM_BLOCK = REGISTRY.register("aluminum_block", () -> new AluminumBlockBlock());
	public static final RegistryObject<Block> RAW_ALUMINUM_BLOCK = REGISTRY.register("raw_aluminum_block", () -> new RawAluminumBlockBlock());
	public static final RegistryObject<Block> SULFUR_BLOCK = REGISTRY.register("sulfur_block", () -> new SulfurBlockBlock());
	public static final RegistryObject<Block> QUARTZ_LAMP_ACTIVE = REGISTRY.register("quartz_lamp_active", () -> new QuartzLampActiveBlock());
	public static final RegistryObject<Block> SANDSTONE_FIRE_TRAP_IGNITED = REGISTRY.register("sandstone_fire_trap_ignited", () -> new SandstoneFireTrapIgnitedBlock());
}
